# Generated by Django 3.0.7 on 2020-06-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0004_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedinuser',
            name='session_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
